---
title: "Final_project"
author: "Shijie Qu & Yifan Song"
date: "12/1/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
realEst_data = read.csv("ames_housing_data_PROJECT2018.csv")
library(tidyverse)
library(car)
library(GGally)
glimpse(data)
```

### AR-1
```{r}
ggpairs(data = realEst_data, columns = c ("SalePrice","LotArea","YearBuilt","SqFt"))
```

```{r}
## SalePrice vs LotArea

# take log of both
plot(log(realEst_data$LotArea),log(realEst_data$SalePrice),xlab = "log(LotArea)",ylab = "log(SalePrice)",main = "log(SalePrice) vs log(LotArea)")
lm1 = lm(log(SalePrice)~log(LotArea),data = realEst_data)
abline(lm1)
summary(lm1)
```

```{r}
## SalePrice vs YearBuilt

# take log of only SalePrice
plot(realEst_data$YearBuilt,log(realEst_data$SalePrice),xlab = "YearBuilt",ylab = "log(SalePrice)",main = "log(SalePrice) vs YearBuilt")
lm2 = lm(log(SalePrice)~YearBuilt,data = realEst_data)
abline(lm2)
summary(lm2)

# try quadratic model
lm2_1 = lm(log(SalePrice)~YearBuilt + I(YearBuilt^2),data = realEst_data);

summary(lm2_1)
plot(realEst_data$YearBuilt,log(realEst_data$SalePrice),xlab = "YearBuilt",ylab = "log(SalePrice)",main = "log(SalePrice) vs YearBuilt",col="red")
points(realEst_data$YearBuilt,fitted(lm2_1),col="blue");
```

```{r}
## SalePrice vs SqrFt

# take log of only SalePrice
plot(realEst_data$SqFt,log(realEst_data$SalePrice),xlab = "SqFt",ylab = "log(SalePrice)",main = "log(SalePrice) vs log(LotArea)")
lm3 = lm(log(SalePrice)~SqFt , data = realEst_data)
abline(lm3)
summary(lm3)
```

### AR-2
```{r}
## Build linear model
mod = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt,data = realEst_data)
summary(mod)

```


```{r}
##???Check interaction
AIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:log(LotArea),data = realEst_data)) - AIC(mod)
BIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:log(LotArea),data = realEst_data)) - BIC(mod)
AIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:YearBuilt,data = realEst_data)) - AIC(mod)
BIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:YearBuilt,data = realEst_data)) - BIC(mod)
AIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+log(LotArea):YearBuilt,data = realEst_data)) - AIC(mod)
BIC(lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+log(LotArea):YearBuilt,data = realEst_data)) - BIC(mod)
anova(mod, lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:log(LotArea),data = realEst_data))
anova(mod, lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+SqFt:YearBuilt,data = realEst_data))
anova(mod, lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+log(LotArea):YearBuilt,data = realEst_data))
```

```{r}
##Residual plot and QQ-plot
plot(fitted(mod),resid(mod),main="Residual plot of the model")
abline(h=0)
qqnorm(resid(mod));qqline(resid(mod))
```

### AR-3
```{r}
# try to use see whether use factored variable or continuous variable

HalfBath_Fact = as.factor(realEst_data$HalfBath)
FullBath_Fact = as.factor(realEst_data$FullBath)
Bedroom_Fact = as.factor(realEst_data$Bedrooms)
Room_Fact = as.factor(realEst_data$Rooms)

# decide whether combine half&full bath 

# decide rooms to be continuous or factored variable
roomFact = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+Room_Fact+Style,data = realEst_data)
roomCont = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+Rooms+Style,data = realEst_data)
diffRoom = BIC(roomFact) - BIC(roomCont)
diffRoom

# decide HalfBath to be continuous or factored variable
HalfBathFact = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath_Fact+Style,data = realEst_data)
HalfBathCont = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+Style,data = realEst_data)
diffHalfBath = BIC(HalfBathFact) - BIC(HalfBathCont)
diffHalfBath

# decide FullBath to be continuous or factored variable
FullBathFact = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+FullBath_Fact+Style,data = realEst_data)
FullBathCont = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+FullBath+Style,data = realEst_data)
diffFullBath = BIC(FullBathFact) - BIC(FullBathCont)
diffFullBath

# decide Bedrooms to be continuous or factored variable
BedroomsFact = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+Bedroom_Fact+Style,data = realEst_data)
BedroomsCont = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+Bedrooms+Style,data = realEst_data)
diffBedrooms = BIC(BedroomsFact) - BIC(BedroomsCont)
diffBedrooms

# decide whether should replace Rooms as a predictor
WithRooms = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+FullBath+Bedroom_Fact+Room_Fact+Style,data = realEst_data)
NoRooms = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+FullBath+Bedroom_Fact+Style,data = realEst_data)
diffR = BIC(WithRooms) - BIC(NoRooms)
diffR

# decide whether should replace other type of rooms (keep only with the # of total rooms)
WithOtherRooms = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+FullBath+Bedroom_Fact+Room_Fact+Style,data = realEst_data)
NoOtherRooms = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+Room_Fact+Style,data = realEst_data)
diffO = BIC(WithOtherRooms) - BIC(NoOtherRooms)
diffO
```

```{r}
# decide whether to combine half&full bath to bath
bath = realEst_data$FullBath+0.5*realEst_data$HalfBath
combineBath = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+bath+Bedroom_Fact+Style,data = realEst_data)

seperateBath = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+FullBath+Bedroom_Fact+Style,data = realEst_data)

diffR = BIC(combineBath) - BIC(seperateBath)
diffR

```
## therefore, use factored value bedroom and continuous for full bath and half bath & without rooms



```{r}

# stepwise regression by AIC
null = lm(log(SalePrice)~1, data = realEst_data )
full = lm(log(SalePrice)~SqFt+log(LotArea)+YearBuilt+HalfBath+FullBath+Bedroom_Fact+Style,data = realEst_data)

library(MASS)
stepAIC(full,scope = list(lower=null,upper=full),direction="both",k=log(dim(realEst_data)[1]));



```


```{r}
newlm = stepAIC(null,scope = list(upper=full),direction="both",k=log(dim(realEst_data)[1]));
newlm$terms
```


```{r}
##Residual plot and QQ-plot
summary(newlm)
plot(newlm$fitted.values,newlm$residuals,main="Residual plot of the model")
abline(h=0)
qqnorm(newlm$residuals);qqline(newlm$residuals)
```



### AR-4

```{r}
summary(newlm)
```

```{r}
# suppose sqFt = 1995, YearBuilt = 2013, Style = 2 story, Bedrooms = 3, FullBath = 2, halfBath = 2, Rooms = 10, LotArea = 15500.

d = data.frame(SqFt = 1995, YearBuilt = 2013, Style = '2Story', Bedroom_Fact = '3', LotArea = 15500, HalfBath = 2);
pridict_model = predict(newlm, d, se.fit = TRUE)
price = pridict_model$fit
price = exp(price)
price


```

```{r}
# 95% prediction interval for log(salePrize)
logPI = predict(newlm, newdata=d, interval="prediction", level=.95)
logPI
realPI = exp(logPI)
realPI

```


